//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centipede.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Centipede.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string BranchAction_BranchAction_Branch {
            get {
                return ResourceManager.GetString("BranchAction_BranchAction_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string BranchAction_ConditionSource_False {
            get {
                return ResourceManager.GetString("BranchAction_ConditionSource_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next action if condition returns true (otherwise, proceed normally).
        /// </summary>
        public static string BranchAction_Usage {
            get {
                return ResourceManager.GetString("BranchAction_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action if True
        ///.
        /// </summary>
        public static string BranchActionDisplayName {
            get {
                return ResourceManager.GetString("BranchActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition
        ///.
        /// </summary>
        public static string BranchActionI18N_Condition_DisplayName {
            get {
                return ResourceManager.GetString("BranchActionI18N_Condition_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BranchActionUsage.
        /// </summary>
        public static string BranchActionUsage {
            get {
                return ResourceManager.GetString("BranchActionUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action if false.
        /// </summary>
        public static string BranchDisplayControl_BranchDisplayControl_Action_if_false {
            get {
                return ResourceManager.GetString("BranchDisplayControl_BranchDisplayControl_Action_if_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string BranchDisplayControl_BranchDisplayControl_Condition {
            get {
                return ResourceManager.GetString("BranchDisplayControl_BranchDisplayControl_Condition", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon Centipede {
            get {
                object obj = ResourceManager.GetObject("Centipede", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error: cannot continue
        ///{0}.
        /// </summary>
        public static string CentipedeCore_RunJob_FatalError {
            get {
                return ResourceManager.GetString("CentipedeCore_RunJob_FatalError", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Complete_OK {
            get {
                object obj = ResourceManager.GetObject("Complete_OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CriticalError {
            get {
                object obj = ResourceManager.GetObject("CriticalError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Action executed.
        /// </summary>
        public static string DemoAction_DoAction_Demo_Action_executed {
            get {
                return ResourceManager.GetString("DemoAction_DoAction_Demo_Action_executed", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon generic {
            get {
                object obj = ResourceManager.GetObject("generic", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon If {
            get {
                object obj = ResourceManager.GetObject("If", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save?.
        /// </summary>
        public static string MainWindow_AskSave_Do_you_wish_to_save {
            get {
                return ResourceManager.GetString("MainWindow_AskSave_Do_you_wish_to_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string MainWindow_AskSave_Unsaved_Changes {
            get {
                return ResourceManager.GetString("MainWindow_AskSave_Unsaved_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string MainWindow_CompletedHandler_Finished {
            get {
                return ResourceManager.GetString("MainWindow_CompletedHandler_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job did not finish..
        /// </summary>
        public static string MainWindow_CompletedHandler_Job_did_not_finish_ {
            get {
                return ResourceManager.GetString("MainWindow_CompletedHandler_Job_did_not_finish_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job finished successfully..
        /// </summary>
        public static string MainWindow_CompletedHandler_Job_finished_successfully_ {
            get {
                return ResourceManager.GetString("MainWindow_CompletedHandler_Job_finished_successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MainWindow_ErrorHandler_Error {
            get {
                return ResourceManager.GetString("MainWindow_ErrorHandler_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string MainWindow_ErrorHandler_Error_ {
            get {
                return ResourceManager.GetString("MainWindow_ErrorHandler_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred in .
        /// </summary>
        public static string MainWindow_ErrorHandler_Error_occurred_in_ {
            get {
                return ResourceManager.GetString("MainWindow_ErrorHandler_Error_occurred_in_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was:.
        /// </summary>
        public static string MainWindow_ErrorHandler_Message_was_ {
            get {
                return ResourceManager.GetString("MainWindow_ErrorHandler_Message_was_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        public static string MainWindow_LoadBtn_Click_Save_changes_ {
            get {
                return ResourceManager.GetString("MainWindow_LoadBtn_Click_Save_changes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string MainWindow_LoadBtn_Click_Unsaved_Changes {
            get {
                return ResourceManager.GetString("MainWindow_LoadBtn_Click_Unsaved_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask For Values.
        /// </summary>
        public static string MainWindow_MainWindow_ActionName_Ask_For_Values {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_ActionName_Ask_For_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Action.
        /// </summary>
        public static string MainWindow_MainWindow_ActionName_Demo_Action {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_ActionName_Demo_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Filename.
        /// </summary>
        public static string MainWindow_MainWindow_ActionName_Get_Filename {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_ActionName_Get_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Messagebox.
        /// </summary>
        public static string MainWindow_MainWindow_ActionName_Show_Messagebox {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_ActionName_Show_Messagebox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} variable {{{1}}} : {2}.
        /// </summary>
        public static string MainWindow_OnVariablesOnRowChanged_Message_Text {
            get {
                return ResourceManager.GetString("MainWindow_OnVariablesOnRowChanged_Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string MainWindow_Program_ActionStatus_Running {
            get {
                return ResourceManager.GetString("MainWindow_Program_ActionStatus_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centipede.
        /// </summary>
        public static string MainWindow_Text_Centipede {
            get {
                return ResourceManager.GetString("MainWindow_Text_Centipede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centipede - {0}{1}.
        /// </summary>
        public static string MainWindow_Text_Centipede____0__1_ {
            get {
                return ResourceManager.GetString("MainWindow_Text_Centipede____0__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string MainWindow_UpdateHandlerDone_Completed {
            get {
                return ResourceManager.GetString("MainWindow_UpdateHandlerDone_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable {0}: {1} - {2}.
        /// </summary>
        public static string MainWindow_VariableUpdated {
            get {
                return ResourceManager.GetString("MainWindow_VariableUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://getsatisfaction.com/centipede.
        /// </summary>
        public static string MainWindow_visitGetSatisfactionToolStripMenuItem_Click_GetSatisfaction_Url {
            get {
                return ResourceManager.GetString("MainWindow_visitGetSatisfactionToolStripMenuItem_Click_GetSatisfaction_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Actions Added.
        /// </summary>
        public static string Program_RunJob_No_Actions_Added {
            get {
                return ResourceManager.GetString("Program_RunJob_No_Actions_Added", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon pycon {
            get {
                object obj = ResourceManager.GetObject("pycon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap StatusAnnotation_Run {
            get {
                object obj = ResourceManager.GetObject("StatusAnnotation_Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ThumbnailView {
            get {
                object obj = ResourceManager.GetObject("ThumbnailView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en-gb&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Welcome To Centipede&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        .welcomeBody
        ///        {
        ///            font-family: Microsoft Sans Serif, sans-serif;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body class=&quot;welcomeBody&quot;&gt;
        ///    &lt;section&gt;
        ///        &lt;h1&gt;
        ///            Welcome to Centipede
        ///        &lt;/h1&gt;
        ///        &lt;p&gt;
        ///            Centipede is a tool for automating stuff.
        ///        &lt;/p&gt;
        ///        &lt;p&gt;Please submit feedback on the &lt;a href=&quot;https://getsatisfaction.com/cen [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeScreen {
            get {
                return ResourceManager.GetString("WelcomeScreen", resourceCulture);
            }
        }
    }
}
