//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centipede.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Centipede.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action if false.
        /// </summary>
        public static string BranchDisplayControl_BranchDisplayControl_Action_if_false {
            get {
                return ResourceManager.GetString("BranchDisplayControl_BranchDisplayControl_Action_if_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string BranchDisplayControl_BranchDisplayControl_Condition {
            get {
                return ResourceManager.GetString("BranchDisplayControl_BranchDisplayControl_Condition", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon Centipede {
            get {
                object obj = ResourceManager.GetObject("Centipede", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Complete_OK {
            get {
                object obj = ResourceManager.GetObject("Complete_OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CriticalError {
            get {
                object obj = ResourceManager.GetObject("CriticalError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Action executed.
        /// </summary>
        public static string DemoAction_DoAction_Demo_Action_executed {
            get {
                return ResourceManager.GetString("DemoAction_DoAction_Demo_Action_executed", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon generic {
            get {
                object obj = ResourceManager.GetObject("generic", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon If {
            get {
                object obj = ResourceManager.GetObject("If", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string MainWindow_CompletedHandler_Finished {
            get {
                return ResourceManager.GetString("MainWindow_CompletedHandler_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MainWindow_ErrorHandler_Error {
            get {
                return ResourceManager.GetString("MainWindow_ErrorHandler_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string MainWindow_ErrorHandler_Error_ {
            get {
                return ResourceManager.GetString("MainWindow_ErrorHandler_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred in .
        /// </summary>
        public static string MainWindow_ErrorHandler_Error_occurred_in_ {
            get {
                return ResourceManager.GetString("MainWindow_ErrorHandler_Error_occurred_in_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was:.
        /// </summary>
        public static string MainWindow_ErrorHandler_Message_was_ {
            get {
                return ResourceManager.GetString("MainWindow_ErrorHandler_Message_was_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        public static string MainWindow_LoadBtn_Click_Save_changes_ {
            get {
                return ResourceManager.GetString("MainWindow_LoadBtn_Click_Save_changes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string MainWindow_LoadBtn_Click_Unsaved_Changes {
            get {
                return ResourceManager.GetString("MainWindow_LoadBtn_Click_Unsaved_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centipede.
        /// </summary>
        public static string MainWindow_Text_Centipede {
            get {
                return ResourceManager.GetString("MainWindow_Text_Centipede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centipede - {0}{1}.
        /// </summary>
        public static string MainWindow_Text_Centipede____0__1_ {
            get {
                return ResourceManager.GetString("MainWindow_Text_Centipede____0__1_", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon pycon {
            get {
                object obj = ResourceManager.GetObject("pycon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap StatusAnnotation_Run {
            get {
                object obj = ResourceManager.GetObject("StatusAnnotation_Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ThumbnailView {
            get {
                object obj = ResourceManager.GetObject("ThumbnailView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
